#!/bin/bash
~/document/compiler/cool/assignments/PA2/lexer $* | ~/document/compiler/cool/assignments/PA3/parser $* | ~/document/compiler/cool/assignments/PA4/semant $* | ~/document/compiler/cool/assignments/PA5/cgen $*
